const VIDEO_NOTIFIED_THREE_MONTHS = 3;
const VIDEO_NOTIFIED_ONE_MONTH = 1;
const VIDEO_NOTIFIED_INTERVAL_ONE_WEEK = 1;
const VIDEO_NOTIFIED_INTERVAL_THREE_DAYS = 3;
const VIDEO_NOTIFIED_START_SIX_DAYS = 6;
const VIDEO_NOTIFIED_END_NINE_DAYS = 9;
const THREE_MONTHS = 'THREE MONTHS';
const ONE_MONTH = 'ONE MONTH';
const ONE_WEEK = 'ONE WEEK';
const OPENCAST_EVENTS_PATH = '/api/events/';
const OPENCAST_SERIES_PATH = '/api/series/';
const IAM_GROUPS_PATH_PREFIX = '/iam/groups/group/';
const IAM_GROUPS_PATH_POSTFIX = '/members';
const IAM_GROUP_PREFIXES = ['grp-', 'hy-', 'sys-'];
const IAM_ACCOUNT_EMAIL = '/iam/groups/account/emails';
const TRASH = 'trash';
const EXPIRATIONMESSAGE = 'Vanhenemisviesti';

module.exports = {
    VIDEO_NOTIFIED_THREE_MONTHS,
    VIDEO_NOTIFIED_ONE_MONTH,
    VIDEO_NOTIFIED_INTERVAL_ONE_WEEK,
    VIDEO_NOTIFIED_INTERVAL_THREE_DAYS,
    VIDEO_NOTIFIED_START_SIX_DAYS,
    VIDEO_NOTIFIED_END_NINE_DAYS,
    THREE_MONTHS,
    ONE_MONTH,
    ONE_WEEK,
    OPENCAST_EVENTS_PATH,
    OPENCAST_SERIES_PATH,
    IAM_GROUPS_PATH_PREFIX,
    IAM_GROUPS_PATH_POSTFIX,
    IAM_GROUP_PREFIXES,
    OPENCAST_SERIES_PATH,
    TRASH,
    EXPIRATIONMESSAGE,
    IAM_ACCOUNT_EMAIL
};
