SELECT VIDEO_ID, TO_CHAR(ARCHIVED_DATE, 'DD.MM.YYYY') ARCHIVED_DATE FROM VIDEOS
            WHERE ARCHIVED_DATE <= $1 and ACTUAL_ARCHIVED_DATE IS NULL and ERROR_DATE IS NULL and NOTIFICATION_SENT_AT IS NULL ORDER BY VIDEO_CREATION_DATE ASC;
